### ISSUE TITLE
FKF site down at HA start -> integration does not load

### ISSUE THREAD

**Issue by nagyrobi** [amaximus/fkf-garbage-collection#15]
Lately we experience that FKF's website becomes unavailable for various periods of time. If somebody starts/restarts HA during such a period, the component does not load at all and generates this error in the log:

```
2021-11-08 19:20:30 ERROR (MainThread) [homeassistant.components.sensor] fkf_garbage_collection: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 651, in async_device_update
    await task
  File "/config/custom_components/fkf_garbage_collection/sensor.py", line 349, in async_update
    fkfdata = await async_get_fkfdata(self)
  File "/config/custom_components/fkf_garbage_collection/sensor.py", line 197, in async_get_fkfdata
    async with self._session.post(url, data=payload, headers=headers) as response:
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 890, in start
    message, payload = await self._protocol.read()  # type: ignore
  File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 604, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

```

The situation can only be recovered by restarting HA when FKF website is available.

My suggestion is to avoid this, is to handle this error, and load the component with the sensors set to unavailable and not current (maybe reload the last values from recorder). The component should re-check periodically for the site becoming available and update the sensors accordingly after that.

**Comment by amaximus** [comment]
0.4.1 fixes the reported issue.

Please update the integration, test on your side too and get back to me with results.

**Comment by nagyrobi** [comment]
Updated, behavior still runs in error:
```
2021-11-13 08:13:05 ERROR (MainThread) [homeassistant.components.sensor] fkf_garbage_collection: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 651, in async_device_update
    await task
  File "/config/custom_components/fkf_garbage_collection/sensor.py", line 362, in async_update
    fkfdata = await async_get_fkfdata(self)
  File "/config/custom_components/fkf_garbage_collection/sensor.py", line 185, in async_get_fkfdata
    async with self._session.get(url) as response:
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 890, in start
    message, payload = await self._protocol.read()  # type: ignore
  File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 604, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
```

**Comment by amaximus** [comment]
Just pushed a release addressing the Server Disconnected exception when getting the cookie.

Please update the integration and get back to me with results.

**Comment by nagyrobi** [comment]
No more error in the log, but attributes data is incorrect:
```
next_communal_days: null
next_green_days: 1
next_selective_days: null
calendar_lang: en
provider: Data provided by fkf.hu
friendly_name: FKF hulladék
icon: mdi:trash-can-outline
```

Most important is missing the `current` attribute, which should be present and set to `false` in cases like this.
Additionally it would be nice to show cached data from the last successfull parsing...

**Comment by amaximus** [comment]
Just pushed 0.4.4 that will set the `current` attribute to `false` and old/outdted data will populate the attributes (instead of null).

Please update the integration and get back to me with results.

**Comment by amaximus** [comment]
Recently pushed version (0.4.5) adds timeout to http requests.

Please update the integration, check it on your side too and get back to me with results.

**Comment by amaximus** [comment]
Any update on this issue?

**Comment by nagyrobi** [comment]
Looks good now.
