### ISSUE TITLE
2021.12 error

### ISSUE THREAD

**Issue by nagyrobi** [amaximus/fkf-garbage-collection#18]
```
2021-12-12 11:04:27 ERROR (MainThread) [homeassistant.components.sensor] fkf_garbage_collection: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 684, in async_device_update
    await task
  File "/config/custom_components/fkf_garbage_collection/sensor.py", line 369, in async_update
    fkfdata = await async_get_fkfdata(self)
  File "/config/custom_components/fkf_garbage_collection/sensor.py", line 271, in async_get_fkfdata
    _LOGGER.debug("Fetch info for %s/%s/%s: %s", self._zipcode, self._publicplace, self._housenr, s)
UnboundLocalError: local variable 's' referenced before assignment
```

**Comment by amaximus** [comment]
Thanks for the heads-up.

Newer release 0.4.6 fixes the issue.

Please upgrade your custom integration, test and get back to me with results.

**Comment by nagyrobi** [comment]
Also warning:
`2021-12-13 14:24:01 WARNING (MainThread) [homeassistant.helpers.entity] Entity sensor.fkf_hulladek (<class 'custom_components.fkf_garbage_collection.sensor.FKFGarbageCollectionSensor'>) implements device_state_attributes. Please report it to the custom component author.`

**Comment by amaximus** [comment]
Any update on this issue?

**Comment by nagyrobi** [comment]
Looks good now.
